# Generated by Django 5.0.1 on 2024-08-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='sam', max_length=30),
            preserve_default=False,
        ),
    ]
