# Generated by Django 5.0.1 on 2024-08-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='customer_books', to='app_store.book'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='countt',
            field=models.IntegerField(default=0),
        ),
    ]
