# Generated by Django 5.0.1 on 2024-10-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
