# Generated by Django 5.0.1 on 2024-10-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0006_customer_is_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_delete_book', 'Can delete book')]},
        ),
    ]
