# Generated by Django 5.0.1 on 2024-10-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0007_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
